spring:
  app:
    jwtSecret: mySecretKey123
    jwtExpirationMs: 3000000000000000000000000

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5050
